"use client";

import { useState } from "react";

export default function QuizBuilder({ value, onChange }) {
  const [questions, setQuestions] = useState(value || []);
  function update(index, field, next) { const copy = [...questions]; copy[index] = { ...copy[index], [field]: next }; setQuestions(copy); onChange(copy); }
  function addQuestion() { const next = [...questions, { question: "", type: "mcq", options: ["", "", "", ""], correctAnswer: "", points: 1 }]; setQuestions(next); onChange(next); }
  function removeQuestion(index) { const next = questions.filter((_, itemIndex) => itemIndex !== index); setQuestions(next); onChange(next); }
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><p className="text-sm font-bold">Quiz questions</p><p className="text-xs text-[#6680a7]">Students will see the question, options, and submit one attempt.</p></div><button type="button" onClick={addQuestion} className="rounded-lg bg-[#e5f0ff] px-3 py-2 text-xs font-bold text-[#1675ed]">+ Add question</button></div>{questions.map((item, index) => <div key={index} className="rounded-xl border border-[#dce8f7] bg-[#f7fbff] p-4"><div className="flex items-start justify-between gap-3"><span className="text-xs font-bold text-[#6680a7]">Question {index + 1}</span><button type="button" onClick={() => removeQuestion(index)} className="text-xs font-bold text-[#d05a63]">Remove</button></div><input value={item.question} onChange={(event) => update(index, "question", event.target.value)} placeholder="Write the question" className="mt-3 w-full rounded-lg border border-[#dce8f7] bg-white px-3 py-2 text-sm" required /><select value={item.type} onChange={(event) => update(index, "type", event.target.value)} className="mt-3 rounded-lg border border-[#dce8f7] bg-white px-3 py-2 text-sm"><option value="mcq">Multiple choice</option><option value="text">Short answer</option></select>{item.type === "mcq" && <div className="mt-3 grid gap-2 sm:grid-cols-2">{item.options.map((option, optionIndex) => <input key={optionIndex} value={option} onChange={(event) => { const options = [...item.options]; options[optionIndex] = event.target.value; update(index, "options", options); }} placeholder={`Option ${optionIndex + 1}`} className="rounded-lg border border-[#dce8f7] bg-white px-3 py-2 text-sm" required />)}</div>}<div className="mt-3 grid gap-2 sm:grid-cols-2"><input value={item.correctAnswer} onChange={(event) => update(index, "correctAnswer", event.target.value)} placeholder={item.type === "mcq" ? "Correct option text" : "Accepted answer"} className="rounded-lg border border-[#dce8f7] bg-white px-3 py-2 text-sm" required /><input type="number" min="1" value={item.points} onChange={(event) => update(index, "points", Number(event.target.value))} placeholder="Points" className="rounded-lg border border-[#dce8f7] bg-white px-3 py-2 text-sm" /></div></div>)}{!questions.length && <button type="button" onClick={addQuestion} className="w-full rounded-xl border border-dashed border-[#a8c9ef] py-5 text-sm font-semibold text-[#1675ed]">Add the first question</button>}</div>;
}
